algoritmo "Escolha do Usuário"
var
cont,num, intervalo: inteiro

inicio
      escreval(" Até que número você deseja contar?")
      leia(num)
      escreval(" Qual o intervalo que você quer contar")
      leia(intervalo)
      cont <- 0
                enquanto (cont<=num) faca
                escreva(cont)
                cont <- cont + intervalo
                fimenquanto
      escreval(" ACABOU!")
fimalgoritmo
